name: CI

on:
  push:
    branches:
      - main  # adjust the branch name as needed
  pull_request:
    branches:
      - main  # adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run ESLint, Prettier, and tests
      run: |
        npm run lint
        npm run prettier:check
        npm test
